# Generated by Django 5.1.1 on 2024-09-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo')], max_length=100)),
                ('cpu_type', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=100)),
                ('clock_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('in_stock', models.BooleanField(default=True)),
                ('manufacture_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('ram_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.ram')),
            ],
        ),
    ]
