# Generated by Django 5.1.1 on 2024-09-25 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RamSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(unique=True, verbose_name='Кількість ОЗП')),
            ],
        ),
        migrations.CreateModel(
            name='RamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4, unique=True, verbose_name='Тип ОЗП')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=100, verbose_name='Назва збірки')),
                ('cpu_type', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=100, verbose_name='Тип процесора')),
                ('cpu_series', models.CharField(choices=[('Core i3', 'Core i3'), ('Core i5', 'Core i5'), ('Core i7', 'Core i7'), ('Core i9', 'Core i9'), ('Ryzen 3', 'Ryzen 3'), ('Ryzen 5', 'Ryzen 5'), ('Ryzen 7', 'Ryzen 7'), ('Ryzen 9', 'Ryzen 9')], max_length=100, verbose_name='Серія процесора')),
                ('cpu_model', models.CharField(max_length=7, verbose_name='Модель процесора')),
                ('clock_speed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Тактова частота')),
                ('gpu_type', models.CharField(choices=[('GeForce RTX', 'GeForce RTX'), ('GeForce GTX', 'GeForce GTX'), ('Radeon RX', 'Radeon RX')], max_length=100, verbose_name='Тип відеокарти')),
                ('gpu_model', models.CharField(max_length=6, verbose_name='Модель відеокарти')),
                ('gpu_ram', models.CharField(max_length=6, verbose_name="Кількість відеопам'яті")),
                ('disk_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('M2', 'M2')], max_length=3, verbose_name='Накопичувач')),
                ('disk_value', models.IntegerField(verbose_name='Ємність')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Наявність')),
                ('manufacture_date', models.DateField(verbose_name='Дата виготовлення')),
                ('image', models.ImageField(blank=True, null=True, upload_to='computers/', verbose_name='Фото')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ram_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.ramsize')),
                ('ram_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.ramtype')),
            ],
        ),
    ]
