# Generated by Django 5.1.1 on 2024-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='description',
            field=models.TextField(max_length=300, null=True, verbose_name='Опис для збірки'),
        ),
    ]
